# Generated by Django 4.0.5 on 2022-06-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='puechase_date',
            new_name='purchase_date',
        ),
    ]
