# Generated by Django 4.0.5 on 2022-06-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_puechase_date_orders_purchase_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
